# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

vars:
  GREETING: Hello, world!

tasks:
  default:
    desc: Print a greeting message
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  build:
    desc: Compile all asm files
    cmds:
      - dasm *.asm -f3 -v0 -ocartridge.bin -lcartridge.lst -scartridge.sym
  clean:
    desc: Remove generated binary files
    cmds:
      - rm -f *.bin *.lst *.sym